# Generated by Django 3.2.16 on 2025-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='Введите дату своего рождения.', null=True, verbose_name='Дата рождения'),
        ),
    ]
