# Generated by Django 3.2.16 on 2025-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID чата Telegram'),
        ),
    ]
