# Generated by Django 3.2.16 on 2025-08-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineform',
            options={'ordering': ('name',), 'verbose_name': 'форма выпуска', 'verbose_name_plural': 'Формы выпуска'},
        ),
        migrations.AlterModelOptions(
            name='pill',
            options={'verbose_name': 'препарат', 'verbose_name_plural': 'Препараты'},
        ),
    ]
