# Generated by Django 3.2.16 on 2025-08-05 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pillbox', '0003_auto_20250804_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'время напоминания',
                'verbose_name_plural': 'Время напоминания',
            },
        ),
        migrations.CreateModel(
            name='Pillbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Общее количество приема препарата, от 1 до 200', validators=[django.core.validators.MinValueValidator(1, message='Минимум одна'), django.core.validators.MaxValueValidator(200, message='Максимум двести')], verbose_name='Общее клоличество')),
                ('daily_count', models.PositiveSmallIntegerField(help_text='Количесто приема препарата в день, от 1 до 30', validators=[django.core.validators.MinValueValidator(1, message='Минимум одна'), django.core.validators.MaxValueValidator(30, message='Максимум тридцать')], verbose_name='Количество в день')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Дата, с которой начинается прием препарата', verbose_name='Дата начала приема')),
                ('is_active', models.BooleanField(default=True, help_text='Статус активности схемы приема', verbose_name='Активен')),
                ('pill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pillboxes', to='pillbox.pill', verbose_name='Препарат')),
                ('reminder_time', models.ManyToManyField(help_text='Время, когда нужно принимать препарат', to='pillbox.ReminderTime', verbose_name='Время напоминания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillboxes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Таблетница',
                'verbose_name_plural': 'Таблетницы',
                'ordering': ('-start_date',),
            },
        ),
    ]
