# Generated by Django 3.2.16 on 2025-08-05 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0004_pillbox_remindertime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remindertime',
            options={'ordering': ('-time',), 'verbose_name': 'время напоминания', 'verbose_name_plural': 'Время напоминания'},
        ),
        migrations.AlterField(
            model_name='pillbox',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Общее количество приема препарата в шт., от 1 до 200', validators=[django.core.validators.MinValueValidator(1, message='Минимум одна'), django.core.validators.MaxValueValidator(200, message='Максимум двести')], verbose_name='Общее клоличество'),
        ),
        migrations.AlterField(
            model_name='pillbox',
            name='daily_count',
            field=models.PositiveSmallIntegerField(help_text='Количесто приема препарата в день в шт., от 1 до 30', validators=[django.core.validators.MinValueValidator(1, message='Минимум одна'), django.core.validators.MaxValueValidator(30, message='Максимум тридцать')], verbose_name='Количество в день'),
        ),
    ]
