# Generated by Django 3.2.16 on 2025-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
    ]
