# Generated by Django 3.2.16 on 2025-08-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0007_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
