# Generated by Django 3.2.16 on 2025-08-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0008_remove_like_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pill',
            options={'ordering': ('-created_at',), 'verbose_name': 'препарат', 'verbose_name_plural': 'Препараты'},
        ),
    ]
