# Generated by Django 3.2.16 on 2025-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0010_alter_pill_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='unique_manufacturer'),
        ),
    ]
