# Generated by Django 3.2.16 on 2025-08-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок кнопки')),
                ('strong_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок вкладки')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Содержание вкладки')),
            ],
        ),
    ]
