# Generated by Django 3.2.16 on 2025-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordion',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Группа аккардеона'),
        ),
    ]
