# Generated by Django 3.2.16 on 2025-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_accordion_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание вкладки'),
        ),
    ]
