# Generated by Django 3.2.16 on 2025-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_accordion_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accordion',
            options={'verbose_name': 'поле аккордеона', 'verbose_name_plural': 'Аккордеон'},
        ),
        migrations.AlterField(
            model_name='accordion',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Группа аккордеона'),
        ),
    ]
